[book]
title = "CS2 국내반 보충자료"
description = "KSA 정보과학2(CS2) 국내반 보충자료"
language = "ko"
src = "src"

[output.html]
git-repository-url = "https://github.com/SuminHan/book-cs2"
additional-css = ["theme/numbering.css"]

[build]
build-dir = "docs"
